# 适配 Nginx container 反代能力的 Tailscale Sidecar 扩展配置：同时公网与 Tailnet 访问
services:
  ts-sidecar:
    networks:
      nginx-proxy-network: # 改成你的nginx网络名称
        aliases: 
          - ${TS_HOSTNAME:-ts-sidecar} # 可自定义别名，nginx 可通过此名称访问

networks:
  nginx-proxy-network:
    external: true
